#!/bin/bash
# -ws pspec  : set active workspace file
# -wso pspec : set and code open it. meh
# -ws null   : show /return active ws file path.
# -wsx : unset vs ws.
# -h
#  none
cmd="(this) st command help for all active commands. "

echo ''
echo ''
# cat "$HOME/.shorttasks/ascii.txt"
source "$HOME/.shorttasks/lib/banner.sh"
echo 'generated by install/update ...'
echo ''
echo '   short  :      instead of                     '
echo '-------------------------------------------'
cat "$HOME/.shorttasks/lib/help.txt"

read -p "more..." </dev/tty

echo '$ gc "commit message"           - runs in every first level dir that is git enabled.'
echo '$ gc webapp "commit message"    - runs in webapp folder (as long as it is git enabled'
echo '$ gc . "commit message"         - runs in current folder.'
echo '$ gs                            - git status -s for every first level dir having package.json '
